Add Support for Rails 7
marshall-lee/nested_record pull request #13
Opened 2023-08-22 14:17 UTC by mkhairi

2023-11-23 05:54 UTC, mkhairi commented
Hi @marshall-lee, Hope you're well. Could you kindly review this PR when you have a moment? Thanks.

2023-11-23 13:53 UTC, marshall-lee commented
Hi @mkhairi please fix the CI.

2023-11-23 15:35 UTC, marshall-lee commented
@mkhairi Lets drop Ruby 2.5 support, it's way too old.

2023-11-28 22:51 UTC, marshall-lee requested changes

2023-11-28 22:51 UTC, marshall-lee commented on lib/nested_record/lookup_const.rb
> +  end
```suggestion
  # TODO: Remove this when we drop support for Rails < 7.0
  if ActiveSupport::VERSION::MAJOR < 7
    def self.constantize(type_name)
      ActiveSupport::Dependencies.constantize(type_name)
    end
    
    def self.safe_constantize(type_name)
      ActiveSupport::Dependencies.safe_constantize(type_name)
    end
  else
    def self.constantize(type_name)
      type_name.constantize
    end
    
    def self.safe_constantize(type_name)
      type_name.safe_constantize
    end
  end
```

2023-11-29 17:10 UTC, mkhairi commented on lib/nested_record/lookup_const.rb
> +  end
@marshall-lee, Opps.. Seems like it works without any rails version condition here. 😅

2023-11-29 17:36 UTC, marshall-lee commented on lib/nested_record/lookup_const.rb
> +  end
@mkhairi Yes it works but `ActiveSupport::Dependencies.constantize` on older Rails leverages the `ActiveSupport::Dependencies::ClassCache`. We should do it too.

2023-11-30 02:32 UTC, mkhairi commented on lib/nested_record/lookup_const.rb
> +  end
> @mkhairi Yes it works but `ActiveSupport::Dependencies.constantize` on older Rails leverages the `ActiveSupport::Dependencies::ClassCache`. We should do it too.

@marshall-lee, Apologies,  I'm unaware of about this. I have reinstated the Rails version condition based on the previous suggestion.

2023-11-30 18:08 UTC, marshall-lee commented on lib/nested_record/lookup_const.rb
> +  end
@mkhairi Sure, please squash the commits

2023-12-01 19:31 UTC, marshall-lee approved these changes

2023-12-01 19:32 UTC, merged